/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junitexample;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.DisplayName;
import java.util.*;

class AppTest {
    @Test
    @DisplayName("Test the existance of a greeting")
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "App should have a greeting");
    }

    @Test
    @DisplayName("Test for minimal element of an array")
    public void test_find_min_1() {
      int[] a = {5, 1, 7};
      int res = App.find_min(a);
      //assertTrue(res == 1, "The minimum from 5, 1, 7 should be 1");
      assertEquals(res, 1, "The minimum from 5, 1, 7 should be 1");
    }

    @Test
    @DisplayName("Test for inserting an element into an array")
    public void test_insert_1() {
      int[] x = {2, 7};
      int n = 6;
      int[] res = App.insert(x, n);
      int[] expected = {2, 6, 7};
      //assertTrue(Arrays.equals(expected, res));
      assertArrayEquals(expected, res, "The insert did not work properly");
    }



}
