# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #- name: Build with Gradle
    #  run: ./gradlew build
    - name: Run Tests
      run: ./gradlew test
    - name: Store reports
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: |
            build/reports/
            build/test-results/

    - name: Test Reporter
      uses: dorny/test-reporter@v2.1.0
      with:
        name: Test Results  # name for the report
        path: 'build/test-results/test/*.xml'  # Adjust the path to match your test result files
        reporter: java-junit 
